Python sdk improvements
configcat/docs pull request #101
Opened 2022-03-10 10:28 UTC by kp-cat

### Related tickets

https://trello.com/c/FuPidQQt/160-sdk-loglevel-update-python
https://trello.com/c/i4HzNG0Z/105-sdk-getallvalues-python
https://trello.com/c/v1RVkza1/147-sdk-improvements-python

### Description

Pyhton docs update: logging + get_all_values + flag_overrides

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [x] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2022-03-11 13:55 UTC, sigewuzhere requested changes

2022-03-11 13:55 UTC, sigewuzhere commented on website/docs/sdk-reference/python.md
> +| `connect_timeout`                   | How many seconds to wait for the server to make the initial connection (i.e. completing the TCP connection handshake). | 10 |
```suggestion
| `connect_timeout`                   | The number of seconds to wait for the server to make the initial connection (i.e. completing the TCP connection handshake). | 10 |
```

2022-03-11 13:55 UTC, sigewuzhere commented on website/docs/sdk-reference/python.md
> +| `read_timeout`                      | How many seconds to wait for the server to send data before giving up.                               | 30      |
```suggestion
| `read_timeout`                      | The number of seconds to wait for the server to respond before giving up.                               | 30      |
```

2022-03-11 13:55 UTC, sigewuzhere commented on website/docs/sdk-reference/python.md
> +| `connect_timeout`    | How many seconds to wait for the server to make the initial connection (i.e. completing the TCP connection handshake). | 10 |
same as above

2022-03-11 13:55 UTC, sigewuzhere commented on website/docs/sdk-reference/python.md
> +| `read_timeout`       | How many seconds to wait for the server to send data before giving up. | 30 |
same as above

2022-03-11 13:55 UTC, sigewuzhere commented on website/docs/sdk-reference/python.md
> +| `flagOverrides`      | Configures local feature flag & setting overrides. [More about feature flag overrides](#flag-overrides) | None |
Try to avoid the word "configure"

2022-04-01 13:46 UTC, sigewuzhere approved these changes

2022-04-06 10:29 UTC, z4kn4fein approved these changes

2022-04-06 10:32 UTC, merged