Monday integration [DO NOT MERGE]
configcat/docs pull request #110
Opened 2022-04-21 15:33 UTC by laliconfigcat

### Description

Documentation for the monday integration.

### Testing guide

Provide a guideline about how to test the applied changes.

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2022-04-22 13:31 UTC, sigewuzhere requested changes

2022-04-22 13:31 UTC, sigewuzhere commented on website/docs/integrations/monday.md
> +Turn features On / Off right from a linked Item on your Monday board with ConfigCat's Monday App. Also you can add Targeting or Percentage Rules just as easily.
```suggestion
Turn features On / Off right from a linked item on your Monday board with ConfigCat's Monday App. Also you can add targeting or percentage rules just as easily.
```

2022-04-22 13:41 UTC, laliconfigcat commented on website/docs/integrations/monday.md
>  4. Get your ConfigCat Public API credentials: https://app.configcat.com/my-account/public-api-credentials
Done

2022-04-22 13:41 UTC, laliconfigcat commented on website/docs/integrations/monday.md
> +1. Install ConfigCat Feature Flags Monday app to your Monday account.
It will be added later (we don't have the link yet)

2022-05-19 08:27 UTC, sigewuzhere approved these changes

2022-05-19 08:33 UTC, z4kn4fein approved these changes

2022-05-19 08:33 UTC, merged