compile is now deprecated and removed completely Gradle 7+
configcat/docs pull request #144
Opened 2022-09-16 12:46 UTC by vladspatariu

### Description

Our CW Roxana Halati caught this while playing around with feature flags in Java. 

### Requirement checklist

- [ ] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2022-09-16 13:45 UTC, z4kn4fein requested changes

2022-09-16 13:45 UTC, z4kn4fein commented on website/docs/sdk-reference/java.md
> +Old Gradle versions:
I think the new version is enough, we can remove the `compile` one

2022-09-16 13:45 UTC, z4kn4fein commented on website/docs/sdk-reference/java.md
> +implementation group: 'com.configcat', name: 'configcat-java-client', version: '7.+'
```suggestion
implementation "com.configcat:configcat-java-client:7.+"
```

Maybe the shorthand version is a bit better, I'm going to change this in the java repo's examples & docs as well

2022-09-16 13:46 UTC, z4kn4fein commented
Thanks for this heads-up!

2022-09-17 08:54 UTC, sigewuzhere commented
:pray: Nice catch!

2022-09-19 13:44 UTC, z4kn4fein approved these changes

2022-09-20 15:59 UTC, merged