Add default user desciption to the java-sdk docs
configcat/docs pull request #158
Opened 2022-10-13 21:53 UTC by novalisdenahi

### Description

Java-SDK default user option docs update.

### Requirement checklist

- [ ] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2022-10-28 18:14 UTC, sigewuzhere requested changes

2022-10-28 18:14 UTC, sigewuzhere commented on website/docs/sdk-reference/java.md
> +| `flagOverrides(OverrideDataSourceBuilder, OverrideBehaviour)` | Optional, configures local feature flag & setting overrides. [More about feature flag overrides](#flag-overrides).
```suggestion
| `flagOverrides(OverrideDataSourceBuilder, OverrideBehaviour)` | Optional, sets the local feature flag & setting overrides. [More about feature flag overrides](#flag-overrides).                                                                                                                                                                                 |
```

2022-11-03 08:08 UTC, erosb reviewed
belepofázás done.

Further suggestion: you could use type inference for local variables (`var`), it makes the code samples.

Further-further suggestion: please include the minimum supported java version.

2022-12-14 11:18 UTC, sigewuzhere requested changes

2022-12-15 15:58 UTC, sigewuzhere requested changes

2022-12-15 15:58 UTC, sigewuzhere commented on website/docs/sdk-reference/java.md
>  ### 3. Create the _ConfigCat_ client with your _SDK Key_
create and get ...

2022-12-15 15:58 UTC, sigewuzhere commented on website/docs/sdk-reference/java.md
> +This method has no effect on client's created with the deprecated constructor.
```suggestion
This method has no effect on the clients that were created with the deprecated constructor.
```

2022-12-23 11:00 UTC, sigewuzhere commented on website/docs/sdk-reference/java.md
>  ### 3. Create the _ConfigCat_ client with your _SDK Key_
Get the _ConfigCat_ client for your _SDK Key_

2022-12-23 12:11 UTC, sigewuzhere approved these changes

2022-12-23 15:49 UTC, sigewuzhere submitted a review, later dismissed

2022-12-23 15:53 UTC, sigewuzhere approved these changes

2022-12-30 16:24 UTC, z4kn4fein approved these changes

2022-12-30 16:24 UTC, merged