Added additional faq data
configcat/docs pull request #183
Opened 2022-11-22 19:10 UTC by codedbychavez

### Description

Added answers to the following questions:

- Can I sign a data processing agreement with ConfigCat?
- Which data is processed and stored from browsers accessing ConfigCat's CDN to pull feature toggles?
- Is ConfigCat's data only hosted within the EU?
- Is it possible to export feature flags in ConfigCat?
- How can I use AND operators in my targeting rules in ConfigCat?

Shifted the following question up for better alignment with the faq page:
- How can I be sure that my data is safe at ConfigCat?

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2022-11-23 14:53 UTC, sigewuzhere requested changes

2022-11-23 14:53 UTC, sigewuzhere commented on website/src/schema-markup/faq.json
> +                "text": "Yes, ConfigCat have no trouble signing a data processing agreement (DPA)"
```suggestion
                "text": "Yes, ConfigCat is happy to sign a data processing agreement (DPA)"
```

Please update the original one as well

2022-11-23 14:53 UTC, sigewuzhere commented on website/src/schema-markup/faq.json
> +                "text": "ConfigCat don't store anything from browsers. The data flow is one directional - the SDKs are only downloading the config.json files and the feature flag evaluation happens i
```suggestion
                "text": "ConfigCat doesn't store any browser data. The data flow is one directional - the SDKs are only downloading the config.json files and the feature flag evaluation happens in the SDK. ConfigCat doesn't know anything about your users, only those data which you set in your targeting rules."
```
 Please update the original

2022-11-23 14:53 UTC, sigewuzhere commented on website/src/schema-markup/faq.json
> +            "name": "Which data is processed and stored from browsers accessing ConfigCat's CDN to pull feature toggles?",
```suggestion
            "name": "What data is stored or processed from browsers accessing ConfigCat's CDN when pulling feature toggles?",
```
 Please update the original

2022-11-23 14:53 UTC, sigewuzhere commented on website/src/schema-markup/faq.json
> +                "text": "Yes. The percentage-based targeting is sticky by design and consistent across all SDKs.  Also, consider the following:  - All SDKs evaluate the rules in the exact same way. (
```suggestion
                "text": "Yes. The percentage-based targeting is sticky by design and consistent across all SDKs. More on stickiness and consistency: https://configcat.com/docs/advanced/targeting/#stickiness--consistency"
```

2022-11-24 13:55 UTC, sigewuzhere requested changes
I think you missed a note in my previous comments about updating the original answers.

2022-11-24 20:29 UTC, codedbychavez commented
> I think you missed a note in my previous comments about updating the original answers.

@sigewuzhere Did you mean this [https://github.com/configcat/docs/pull/184](https://github.com/configcat/docs/pull/184) ? or maybe I misunderstood. Feel free to let me know.

2022-11-25 08:39 UTC, sigewuzhere commented
> > I think you missed a note in my previous comments about updating the original answers.
> 
> 
> 
> @sigewuzhere Did you mean this [https://github.com/configcat/docs/pull/184](https://github.com/configcat/docs/pull/184) ? or maybe I misunderstood. Feel free to let me know.

Yes those are the ones. If you get comments in a PR, please fix them there. Now, it is hard to see what belongs where.

2022-11-25 12:52 UTC, codedbychavez commented
> > > I think you missed a note in my previous comments about updating the original answers.
> > 
> > 
> > @sigewuzhere Did you mean this #184 ? or maybe I misunderstood. Feel free to let me know.
> 
> @codedbychavez Yes those are the ones. Please add them here and close the other PR, it is hard to track what belongs where.

Alright, will do.

2022-11-25 13:24 UTC, codedbychavez commented
@sigewuzhere Done. You can take another look.

2022-11-30 14:21 UTC, sigewuzhere submitted a review, later dismissed

2022-11-30 19:11 UTC, codedbychavez commented
@sigewuzhere I had to merge master into this branch to resolve merge conflicts. Requesting your review again.

2022-12-01 07:44 UTC, sigewuzhere approved these changes

2022-12-01 12:59 UTC, merged