Documentation of verifying webhook signatures
configcat/docs pull request #187
Opened 2022-11-28 11:37 UTC by z4kn4fein

### Description

Documentation of verifying the calculated signatures of webhooks sent by ConfigCat.

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2022-11-28 12:36 UTC, laliconfigcat approved these changes

2022-11-30 09:51 UTC, sigewuzhere requested changes

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +| `X-ConfigCat-Webhook-ID`           | The webhook request's unique identifier.                                                            |
```suggestion
| `X-ConfigCat-Webhook-ID`           | The webhook request's unique identifier. Different in every request. |
```

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +<img src="/docs/assets/whsk.png" className="zoomable bottom-spaced" alt="signing keys" />
The censored part should be black or white, only the emphasized part should be red.

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +ConfigCat uses `HMAC` with `SHA-256` to sign webhooks. You can retrieve the **signing key(s)** required for the signature calculation from the <a href="https://app.configcat.com/product/webhooks" tar
```suggestion
ConfigCat uses `HMAC` with `SHA-256` to sign webhooks. You can retrieve the **signing key(s)** required for the signature calculation from the <a href="https://app.configcat.com/product/webhooks" target="_blank">ConfigCat Dashboard's webhook page</a>.
```

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +| `X-ConfigCat-Webhook-Signature-V1` | The list of the `base64` encoded HMAC-SHA-256 signatures. (comma delimited, 1 for each signing key) |
```suggestion
| `X-ConfigCat-Webhook-Signature-V1` | The list of the `base64` encoded HMAC-SHA-256 signatures. (comma delimited, 1 signature for each signing key) |
```

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from X-ConfigCat-Webhook-Signature-V1
```suggestion
// retrieved from the X-ConfigCat-Webhook-Signature-V1 request header
```

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from ConfigCat Dashboard
```suggestion
// retrieved from the ConfigCat Dashboard
```

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from X-ConfigCat-Webhook-ID
```suggestion
// retrieved from the X-ConfigCat-Webhook-ID request header
```

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from X-ConfigCat-Webhook-Timestamp
```suggestion
// retrieved from the X-ConfigCat-Webhook-Timestamp request header
```

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from ConfigCat Dashboard
please fix everywhere

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from X-ConfigCat-Webhook-Signature-V1
please fix everywhere

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from X-ConfigCat-Webhook-ID
please fix everywhere

2022-11-30 09:51 UTC, sigewuzhere commented on website/docs/advanced/notifications-webhooks.md
> +// retrieved from X-ConfigCat-Webhook-Timestamp
please fix everywhere

2022-11-30 13:32 UTC, sigewuzhere approved these changes

2022-11-30 16:52 UTC, laliconfigcat approved these changes

2022-11-30 16:53 UTC, merged