Docs of new React SDK features
configcat/docs pull request #198
Opened 2022-12-15 17:58 UTC by adams85

### Description

Docs of new React SDK features

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2022-12-19 11:21 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +  set(key, config) {
Same as in case of the JS SDK. Please note my comments there.

2023-01-20 11:53 UTC, laliconfigcat requested changes

2023-01-20 11:53 UTC, laliconfigcat commented on website/docs/sdk-reference/react.md
> +let userObject = new User(
```suggestion
const userObject = new User(
```

2023-01-20 12:09 UTC, adams85 commented on website/docs/sdk-reference/react.md
> +It is a ConfigCat client instance (`IConfigCatClient`) to access all features of the ConfigCat.
```suggestion
The ConfigCat client instance (`IConfigCatClient`) to access all features of the _ConfigCat SDK_.
```

2023-01-20 12:09 UTC, adams85 commented on website/docs/sdk-reference/react.md
> +It is a helper function to get feature flag value.
```suggestion
A helper function to get the value of a feature flag.
```

2023-01-20 12:09 UTC, adams85 commented on website/docs/sdk-reference/react.md
> +It is the timestamp of the last config update's event.
```suggestion
The timestamp of the last config update's event.
```

2023-01-20 12:12 UTC, adams85 commented
@sige Could you confirm our suggestions and take a look at the PR as a whole so we can finalize it?

2023-01-20 12:13 UTC, adams85 commented
@sigewuzhere Could you confirm our suggestions and take a look at the PR as a whole so we can finalize it?

2023-01-20 14:01 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +> ** ConfigCat SDK hooks are different things than React Hooks. **
```suggestion
> ** ConfigCat SDK hooks are different than React Hooks. **
```

2023-01-20 14:01 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +## Hooks
```suggestion
## SDK Hooks (not React Hooks)
```

2023-01-20 14:02 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +With higher-order component:
```suggestion
Using higher-order component (HOC):
```

2023-01-25 08:24 UTC, adams85 commented on website/docs/sdk-reference/react.md
> +The available options depends on the chosen polling mode. However, there are some common options which can be set in the case of every polling mode:
I'm not sure about this suggestion: https://englishstudypage.com/grammar/in-case-of-vs-in-the-case-of-in-english/

2023-01-25 09:32 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +The available options depends on the chosen polling mode. However, there are some common options which can be set in the case of every polling mode:
No biggie, I'm fine both ways

2023-01-25 09:35 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +| `offline`                | Determines whether the client should be initialized to offline mode or not. [More about offline mode](#online--offline-mode). | `false` |
I will fix it in a separate PR

2023-01-25 09:43 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +Options also include a property named `setupHook`, which you can use to subscribe to the hooks (events) of the SDK at initialization time. [More about hooks](#hooks).
I will fix it in a separate PR

2023-01-25 09:43 UTC, sigewuzhere commented on website/docs/sdk-reference/react.md
> +Options also include a property named `setupHook`, which you can use to subscribe to the hooks (events) of the SDK at initialization time. [More about hooks](#hooks).
I will fix it in a separate PR

2023-01-25 09:45 UTC, sigewuzhere approved these changes

2023-01-27 10:38 UTC, z4kn4fein approved these changes

2023-01-27 10:42 UTC, merged