Updated Android sdk to v10.0.0 Catnip
configcat/docs pull request #357
Opened 2024-01-17 22:08 UTC by novalisdenahi

### Description

Update the Android SDK docs for v10.0.0 (Catnip)

### Trello card

[Trello ticket](https://trello.com/c/wmqPMiXD)

### Notes for QA

The SDK docs updated and the config-v2-sdk-support-table.md

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-01-18 10:12 UTC, sigewuzhere approved these changes

2024-01-29 14:42 UTC, adams85 requested changes
Could you also adapt and add
* this part to the `getValue` section: https://github.com/configcat/docs/blob/f850e29263c8d55df752fb022c734a678eafda03/website/docs/sdk-reference/dotnet.md?plain=1#L156-L185
* this part to the `getValueDetails` section: https://github.com/configcat/docs/blob/f850e29263c8d55df752fb022c734a678eafda03/website/docs/sdk-reference/dotnet.md?plain=1#L207-L210

2024-01-29 17:20 UTC, adams85 submitted a review, later dismissed

2024-01-29 17:21 UTC, z4kn4fein submitted a review, later dismissed

2024-01-30 10:35 UTC, merged