Updated Dart sdk to v4.0.0 Catnip
configcat/docs pull request #365
Opened 2024-01-26 16:17 UTC by novalisdenahi

### Description

Update dart sdk to v4.0.0 (catnip)

### Trello card

[Trello link](https://trello.com/c/oWIaQxAh/337-catnip-dart)

### Notes for QA

The SDK docs updated and the config-v2-sdk-support-table.md

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-01-29 12:19 UTC, sigewuzhere approved these changes

2024-01-29 14:45 UTC, adams85 requested changes
Could you also adapt and add
* this part to the `getValue` section: https://github.com/configcat/docs/blob/f850e29263c8d55df752fb022c734a678eafda03/website/docs/sdk-reference/dotnet.md?plain=1#L156-L185
* this part to the `getValueDetails` section: https://github.com/configcat/docs/blob/f850e29263c8d55df752fb022c734a678eafda03/website/docs/sdk-reference/dotnet.md?plain=1#L207-L210

2024-01-30 16:30 UTC, adams85 approved these changes

2024-02-05 09:44 UTC, adams85 requested changes
In the meantime, we merged the Config V2 docs, which includes some formatting/spelling consistency improvements in the SDK references. See e.g. https://github.com/configcat/docs/commit/6f8d20ce9721d39cbba7a43541aa37613bfdcb94#diff-f1a725410bdd352c87347015b639baff90bc65cc7a1c8b38537e04ae5f8e421e

Please align the PR with these changes.

2024-02-13 15:13 UTC, z4kn4fein submitted a review, later dismissed

2024-02-13 16:24 UTC, adams85 requested changes

2024-02-13 16:24 UTC, adams85 commented on website/docs/sdk-reference/dart.mdx
> +In addition to the types mentioned above, you also have the option to provide `dynamic` for the type parameter regardless of the setting kind.
```suggestion
In addition to the types mentioned above, you also have the option to provide `object`, `object?` or `dynamic` for the type parameter regardless of the setting kind.
```

2024-02-13 16:24 UTC, adams85 commented on website/docs/sdk-reference/dart.mdx
> +| `matchedTargetingRule`      | `TargetingRule?`                     | If the evaluation was based on a Targeting Rule, this field contains that specific rule.  |
```suggestion
| `matchedPercentageOption`   | `PercentageOption?`                  | The Percentage Option (if any) that was used to select the evaluated value. |
| `matchedTargetingRule`      | `TargetingRule?`                     | The Targeting Rule (if any) that matched during the evaluation and was used to return the evaluated value.  |
```

2024-02-13 16:24 UTC, adams85 commented on website/docs/sdk-reference/dart.mdx
> +| `isDefaultValue`            | `bool`                               | True when the default value passed to getValueDetails() is returned due to an error.      |
```suggestion
| `isDefaultValue`            | `bool`                               | True when the default value passed to `getValueDetails()` is returned due to an error.      |
```

2024-02-13 16:24 UTC, adams85 commented on website/docs/sdk-reference/dart.mdx
> +* accept `String` values containing a valid JSON string which can be deserialized to an array of `String`,
https://dart.dev/language/collections#lists

> Perhaps the most common collection in nearly every programming language is the array, or ordered group of objects. In Dart, arrays are [List](https://api.dart.dev/stable/dart-core/List-class.html) objects, so most people just call them lists.

```suggestion
* accept lists or sets of `String`,
* accept `String` values containing a valid JSON string which can be deserialized to a list of `String`,
```

2024-02-13 16:58 UTC, merged