Kotlin sdk catnip update
configcat/docs pull request #389
Opened 2024-03-06 20:29 UTC by novalisdenahi

### Description

Kotlin SDK doc updated with catnip related changes

### Notes for QA

- v2 kotlin doc updated
- kotlin sdk version updated in v1 and v2 compatibility tabel as well

### Requirement checklist

- [ ] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-03-07 09:19 UTC, sigewuzhere approved these changes

2024-03-22 14:22 UTC, adams85 requested changes

2024-03-22 14:22 UTC, adams85 commented on website/docs/sdk-reference/kotlin.mdx
> +* accept `DateTime` and `DateTimeTz` values, which are automatically converted to a second-based Unix timestamp,
```suggestion
* accept `com.soywiz.klock.DateTime` values, which are automatically converted to a second-based Unix timestamp,
```

2024-03-25 09:57 UTC, sigewuzhere approved these changes

2024-03-25 10:05 UTC, adams85 approved these changes

2024-04-02 13:21 UTC, laliconfigcat approved these changes

2024-04-02 13:34 UTC, merged