cpp catnip docs update
configcat/docs pull request #405
Opened 2024-04-02 11:12 UTC by kp-cat

### Description

C++ docs catnip update

### Notes for QA

Check the cpp docs

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-04-02 13:32 UTC, sigewuzhere approved these changes

2024-04-04 10:24 UTC, sigewuzhere submitted a review, later dismissed

2024-04-05 07:22 UTC, laliconfigcat submitted a review, later dismissed

2024-04-05 07:22 UTC, adams85 requested changes

2024-04-05 07:22 UTC, adams85 commented on website/docs/sdk-reference/cpp.mdx
> +| `isDefaultValue`                  | `bool`                               | True when the default value passed to getValueDetails() is returned due to an error.                       |
Looks like something went wrong with the merge.

```suggestion
| `isDefaultValue`                  | `bool`                               | True when the default value passed to `getValueDetails()` is returned due to an error.                       |
```

2024-04-05 09:23 UTC, adams85 approved these changes

2024-04-05 09:25 UTC, merged