[JS-SDK] Add custom logger implementation
configcat/docs pull request #417
Opened 2024-04-14 19:18 UTC by endret

### Description

Added an instruction of custom logger implementation and setup

### Trello card

https://trello.com/c/L6VitCBe/396-custom-logger-implement%C3%A1ci%C3%B3-a-doksiban

### Notes for QA

-

### Requirement checklist

- [X] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-04-15 06:47 UTC, sigewuzhere submitted a review, later dismissed

2024-04-15 07:24 UTC, laliconfigcat requested changes
Please add these changes to the V1 docs as well.

2024-04-15 21:40 UTC, endret commented
> Please add these changes to the V1 docs as well.

Thanks, fixed!

2024-04-16 14:48 UTC, adams85 approved these changes

2024-04-17 07:39 UTC, laliconfigcat approved these changes

2024-04-17 14:05 UTC, sigewuzhere approved these changes

2024-04-17 14:07 UTC, merged