Update java sdk onClientReady hook with ClientReadyState parameter
configcat/docs pull request #449
Opened 2024-06-03 15:31 UTC by novalisdenahi

### Description

Added the new ClientReadyState parameter to the onClientReady hook in the Java SDK.

### Requirement checklist

- [ ] I have validated my changes on a test/local environment.
- [ ] I have added my changes to the V1 and V2 documentations.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-06-04 06:56 UTC, sigewuzhere approved these changes

2024-06-10 08:56 UTC, adams85 requested changes

2024-06-10 08:56 UTC, adams85 commented on website/docs/sdk-reference/java.mdx
> +- `onClientReady(ClientReadyState)`: This event is sent when the SDK reaches the ready state. If the SDK is configured with lazy load or manual polling it's considered ready right after instantiation
```suggestion
- `onClientReady(ClientCacheState)`: This event is sent when the SDK reaches the ready state. If the SDK is configured with lazy load or manual polling it's considered ready right after instantiation.
```

[From what I see](https://github.com/configcat/java-sdk/blob/b36687881452567fbbe1a6d0e91e2e713c03f1ce/src/main/java/com/configcat/ConfigService.java#L72), "with lazy load or manual polling it's considered ready right after instantiation" is no longer true.

If so, I suggest a wording like [this](https://github.com/configcat/docs/blob/master/website/docs/sdk-reference/dotnet.mdx?plain=1#L421).

2024-06-10 15:34 UTC, adams85 requested changes

2024-06-10 15:34 UTC, adams85 commented on website/docs/sdk-reference/java.mdx
> +- `onClientReady(ClientReadyState)`: This event is sent when the SDK reaches the ready state. If the SDK is set up to use lazy loading or manual polling, it's considered ready right after syncing up
```suggestion
- `onClientReady(ClientCacheState)`: This event is sent when the SDK reaches the ready state. If the SDK is set up to use lazy loading or manual polling, it's considered ready right after syncing up with the config cache.
```

2024-06-10 15:44 UTC, adams85 approved these changes

2024-06-14 15:00 UTC, merged