Add logFilter option and Log Filter section to the SDK doc.
configcat/docs pull request #459
Opened 2024-07-02 14:51 UTC by novalisdenahi

### Description

Add logFilter option and Log Filter section to the Java SDK doc.

### Notes for QA

Add logFilter option to the list and Log Filter section to the Java SDK doc.
Add only to the new V2 doc.

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have added my changes to the V1 and V2 documentations.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-07-02 16:07 UTC, adams85 commented on website/docs/sdk-reference/java.mdx
> +    LogFilterFunction filterLogFunction = ( LogLevel logLevel, int eventId, String message, Throwable exception) -> eventId != 1001;
```suggestion
    // Filter out events with id 1001 from the log.
    LogFilterFunction filterLogFunction = (LogLevel logLevel, int eventId, String message, Throwable exception) -> eventId != 1001;
```

2024-07-02 16:07 UTC, adams85 commented on website/docs/sdk-reference/java.mdx
> +> A complex or a badly implemented log filter can affect the SDK efficiency.
```suggestion
> Please make sure that you log filter logic doesn't perform heavy computation and doesn't block the executing thread. A complex or incorrectly implemented log filter can negatively affect the performance of the SDK.
```

2024-07-03 10:37 UTC, adams85 requested changes

2024-07-03 10:37 UTC, adams85 commented on website/docs/sdk-reference/java.mdx
> +> Please make sure that your log filter logic doesn't perform heavy computation and dosen't block the executing thread. A complex or incorrectly implemented log filter can negatively affect the perfo
typo + minor improvement to wording

```suggestion
> Please make sure that your log filter logic doesn't perform heavy computation and doesn't block the executing thread. A complex or incorrectly implemented log filter can degrade the performance of the SDK.
```

2024-07-03 14:16 UTC, adams85 approved these changes

2024-07-03 14:19 UTC, adams85 commented
Please wait with merging until @sigewuzhere takes a look at the PR too.

2024-07-03 14:32 UTC, sigewuzhere approved these changes

2024-07-04 11:29 UTC, merged