unreal sdk news
configcat/docs pull request #467
Opened 2024-07-23 21:27 UTC by kp-cat

### Description

Unreal SDK news

### Notes for QA

Test the links

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [x] I have added my changes to the V1 and V2 documentations.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-07-24 07:38 UTC, laliconfigcat approved these changes

2024-07-24 13:42 UTC, laliconfigcat submitted a review, later dismissed

2024-07-25 13:43 UTC, laliconfigcat approved these changes

2024-07-30 07:15 UTC, laliconfigcat requested changes

2024-07-30 07:15 UTC, laliconfigcat commented on website/docs/sdk-reference/unreal.mdx
> +- Head to the download the latest [ConfigCat.zip](https://github.com/configcat/unreal-engine-sdk/releases/latest/download/ConfigCat.zip) archive. (or any of the previous versions from: [Releases](htt
Just a suggestion, I think it is not necessary to put the other part in brackets.
```suggestion
- Head to the download the latest [ConfigCat.zip](https://github.com/configcat/unreal-engine-sdk/releases/latest/download/ConfigCat.zip) archive or any of the previous versions from: [Releases](https://github.com/configcat/unreal-engine-sdk/releases)
```

2024-07-30 07:15 UTC, laliconfigcat commented on website/docs/sdk-reference/unreal.mdx
> +Add Dependency to your `.Build.cs` file:
Not sure about this.
```suggestion
Add the ConfigCat Dependency to your `.Build.cs` file:
```

2024-07-30 07:15 UTC, laliconfigcat commented on website/versioned_docs/version-V1/sdk-reference/unreal.mdx
> +- Head to the download the latest [ConfigCat.zip](https://github.com/configcat/unreal-engine-sdk/releases/latest/download/ConfigCat.zip) archive. (or any of the previous versions from: [Releases](htt
```suggestion
- Head to the download the latest [ConfigCat.zip](https://github.com/configcat/unreal-engine-sdk/releases/latest/download/ConfigCat.zip) archive or any of the previous versions from: [Releases](https://github.com/configcat/unreal-engine-sdk/releases)
```

2024-07-30 07:15 UTC, laliconfigcat commented on website/versioned_docs/version-V1/sdk-reference/unreal.mdx
> +Add Dependency to your `.Build.cs` file:
not 100% sure
```suggestion
Add the ConfigCat Dependency to your `.Build.cs` file:
```

2024-07-30 14:47 UTC, laliconfigcat submitted a review, later dismissed

2024-07-31 09:09 UTC, z4kn4fein approved these changes

2024-07-31 09:10 UTC, merged