Add OpenFeature providers to SDK reference
configcat/docs pull request #483
Opened 2024-09-05 16:25 UTC by z4kn4fein

### Description

This PR adds a new `OpenFeature Providers` section under the `SDK References` menu that lists and documents all the ConfigCat providers.

### Notes for QA

- Docs -> SDKs -> SDK References -> OpenFeature Providers

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [x] I have added my changes to the V1 and V2 documentations.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-09-05 20:01 UTC, laliconfigcat requested changes

2024-09-05 20:01 UTC, laliconfigcat commented on website/versioned_docs/version-V1/sdk-reference/openfeature/python.mdx
> +The ConfigCat provider translates these evaluation contexts to ConfigCat [User Objects](../../php/#user-object).
```suggestion
The ConfigCat provider translates these evaluation contexts to ConfigCat [User Objects](../../python/#user-object).
```

2024-09-05 20:01 UTC, laliconfigcat commented on website/docs/sdk-reference/openfeature/python.mdx
> +The ConfigCat provider translates these evaluation contexts to ConfigCat [User Objects](../../php/#user-object).
```suggestion
The ConfigCat provider translates these evaluation contexts to ConfigCat [User Objects](../../python/#user-object).
```

2024-09-06 08:46 UTC, z4kn4fein commented on website/versioned_docs/version-V1/sdk-reference/openfeature/js.mdx
> +></script>
Done

2024-09-06 08:47 UTC, laliconfigcat approved these changes

2024-09-06 08:47 UTC, z4kn4fein commented on website/versioned_docs/version-V1/sdk-reference/android.mdx
> +customAttributes.put("SubscriptionType", "Pro");
Heh, they were there, I just didn't hit the save button 🤦

2024-09-06 09:21 UTC, merged