Intellij plugin
configcat/docs pull request #489
Opened 2024-09-19 21:01 UTC by novalisdenahi

### Description

New IntelliJ integration docs.

- The final JetBrains marketplace link is missing (It will be added after the release)
- Until release, the new doc will only be available through the page path. 
- V1 docs will be added after review if necessary 
- Compatible IDEs list may change based on the tests
 
### Trello card

[Trello link](https://trello.com/c/tZEj4YN5/108-intellij-integration)

### Notes for QA
- The final JetBrains marketplace link is missing (It will be added after the release)
- Until release, the new doc will only be available through the page path. 
- V1 docs will be added after review if necessary 
- Compatible IDEs list may change based on the tests 

### Requirement checklist

- [x] I have validated my changes on a test/local environment.
- [ ] I have added my changes to the V1 and V2 documentations.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2024-10-04 12:49 UTC, zoltan-david requested changes

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +description: ConfigCat IntelliJ IDEA Plugin. This is a step-by-step guide on how to use the ConfigCat JetBrains/IntelliJ  Plugin to manage feature flags in your IDEs.
```suggestion
description: ConfigCat IntelliJ IDEA Plugin. This is a step-by-step guide on how to use the ConfigCat JetBrains/IntelliJ Plugin to manage feature flags in your IDEs.
```

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +After you successfully configured your ConfigCat Config account in the `Settings`, you can use the Feature Flags & Settings Tab and:
```suggestion
After you successfully configured your ConfigCat account in the `Settings`, you can use the Feature Flags & Settings Tab and:
```

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +1. Open the `File` > `Settings/Preferences` menu.
```suggestion
1. In your IDE, open the `File` > `Settings/Preferences` menu.
```

Minden bekezdés elején érdemes elmondani, hogy "HOL" kell csinálni az akciókat. Sokszor egyértelmű a userek nagy részének, de néha nem, és nekik tudunk segíteni.

Ugyanígy érdemes elmondani a "HOL"-t, akkor is amikor másik toolra kell váltani a usernek.

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +1. Download the latest release from [GitHub](https://github.com/configcat/intellij-plugin/releases/latest) or from [JetBrains Marketplace](https://github.com/configcat/intellij-plugin/releases/latest
Itt szépen szerepel is a hol (a GitHubon), bár én még talán azt is ideírniám, hogy egy browserben.

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +1. Open the `File` > `Settings/Preferences` menu.
Itt viszont tool váltás történik, szóval kiírnám, hogy melyik toolban kell folytatnia a usernek

```suggestion
1. In your IDE, open the `File` > `Settings/Preferences` menu.
```

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +1. Open the `File` >  `Settings/Preferences` menu.
```suggestion
1. In your IDE, open the `File` >  `Settings/Preferences` menu.
```

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +1. Open the `File` >  `Settings/Preferences` menu.
```suggestion
1. In your IDE, open the `File` >  `Settings/Preferences` menu.
```

2024-10-04 12:49 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +#### Open your Flags on the ConfigCat Dashboard
```suggestion
#### Open your Flags on the ConfigCat Dashboard

```

2024-10-22 06:28 UTC, zoltan-david reviewed
Egy új kérdésem lett. Minden más szupi <3

2024-10-22 06:28 UTC, zoltan-david commented on website/docs/integrations/intellij.mdx
> +- Open a Config on ConfigCat Dashboard.
Ez azt jelenti, hogy a plugin az IDE-ből indítva a usert megnyitja a ConfigCat Configot egy böngészőben?

2024-12-09 17:33 UTC, zoltan-david approved these changes

2024-12-10 09:04 UTC, laliconfigcat approved these changes

2024-12-10 13:32 UTC, merged