swift docs update - logging + sdk improvements
configcat/docs pull request #74
Opened 2021-12-03 00:05 UTC by kp-cat

### Related tickets

https://trello.com/c/o69PnArg/168-sdk-loglevel-update-swift
https://trello.com/c/5TtFIjjG/148-sdk-improvements-swift

### Description

Swift Docs update:
- Logging
- Remove `maxWaitTimeForSyncCallsInSeconds`
- Add `maxInitWaitTimeInSeconds`

### Requirement checklist

- [ ] I have validated my changes on a test/local environment.
- [ ] I have checked the SNYK/Dependabot reports and applied the suggested changes.
- [ ] (Optional) I have updated outdated packages.

2021-12-03 09:34 UTC, z4kn4fein approved these changes

2021-12-06 16:42 UTC, sigewuzhere requested changes

2021-12-06 16:42 UTC, sigewuzhere commented on website/docs/sdk-reference/ios.md
> +Info level logging helps to inspect the feature flag evaluation process:
```suggestion
Info level logging helps to inspect the feature flag evaluation process,
Example log entries:
```

2021-12-06 16:44 UTC, sigewuzhere submitted a review, later dismissed

2021-12-09 07:43 UTC, sigewuzhere approved these changes

2021-12-09 07:44 UTC, sigewuzhere approved these changes

2021-12-14 08:02 UTC, sigewuzhere approved these changes

2021-12-14 14:26 UTC, z4kn4fein commented on website/docs/sdk-reference/ios.md
> -| `dataGovernance`                   | DataGovernance          | Optional, defaults to `global`. Describes the location of your feature flag and setting data within the ConfigCat CDN. This parameter
loglevel is missing from this table

2022-02-25 10:47 UTC, z4kn4fein requested changes

2022-02-25 10:47 UTC, z4kn4fein commented on website/docs/sdk-reference/ios.md
>  > The default level is `.warning`. With `.nolog` you can turn the logging completely off.
```suggestion
```

2022-02-25 10:47 UTC, z4kn4fein commented on website/docs/sdk-reference/ios.md
> +| `.warning` | Errors and Warnings are logged.                                                         |
```suggestion
| `.warning` | Default. Errors and Warnings are logged.                                                         |
```

2022-02-25 14:42 UTC, z4kn4fein approved these changes

2022-02-26 08:36 UTC, sigewuzhere approved these changes

2022-02-28 13:58 UTC, merged